### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aissaoui-Ahmed**
Hi @01walid !
Add new packge!

### CODE REVIEW

**Comment by 01walid** [comment]
@Aissaoui-Ahmed how is this related to Arabic?

**Comment by Aissaoui-Ahmed** [comment]
Check or remove accents in Arabic 
```bash
```

**Comment by 01walid** [comment]
Thanks, it was not clear from the README

**Comment by atefBB** [comment]
<div dir="rtl">@Aissaoui-Ahmed وهل تعتبر الحركات في اللغة العربية accents ؟</div>

**Comment by Aissaoui-Ahmed** [comment]
@atefBB "accent marks"

**Pull request merged**
